//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace ChiKoja.LocationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ILocationService", Namespace="http://tempuri.org/")]
    public partial class LocationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLocationyVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllProvincesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDistrictsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LocationService() {
            this.Url = "http://192.168.42.16/Services/LocationService.svc/PublicService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLocationyVersionCompletedEventHandler GetLocationyVersionCompleted;
        
        /// <remarks/>
        public event GetAllProvincesCompletedEventHandler GetAllProvincesCompleted;
        
        /// <remarks/>
        public event GetAllCitiesCompletedEventHandler GetAllCitiesCompleted;
        
        /// <remarks/>
        public event GetAllDistrictsCompletedEventHandler GetAllDistrictsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILocationService/GetLocationyVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfint GetLocationyVersion() {
            object[] results = this.Invoke("GetLocationyVersion", new object[0]);
            return ((ResponseBaseOfint)(results[0]));
        }
        
        /// <remarks/>
        public void GetLocationyVersionAsync() {
            this.GetLocationyVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetLocationyVersionAsync(object userState) {
            if ((this.GetLocationyVersionOperationCompleted == null)) {
                this.GetLocationyVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocationyVersionOperationCompleted);
            }
            this.InvokeAsync("GetLocationyVersion", new object[0], this.GetLocationyVersionOperationCompleted, userState);
        }
        
        private void OnGetLocationyVersionOperationCompleted(object arg) {
            if ((this.GetLocationyVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocationyVersionCompleted(this, new GetLocationyVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILocationService/GetAllProvinces", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfProvince63bt_SHOU GetAllProvinces() {
            object[] results = this.Invoke("GetAllProvinces", new object[0]);
            return ((ResponseBaseOfArrayOfProvince63bt_SHOU)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllProvincesAsync() {
            this.GetAllProvincesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllProvincesAsync(object userState) {
            if ((this.GetAllProvincesOperationCompleted == null)) {
                this.GetAllProvincesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllProvincesOperationCompleted);
            }
            this.InvokeAsync("GetAllProvinces", new object[0], this.GetAllProvincesOperationCompleted, userState);
        }
        
        private void OnGetAllProvincesOperationCompleted(object arg) {
            if ((this.GetAllProvincesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllProvincesCompleted(this, new GetAllProvincesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILocationService/GetAllCities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfCity63bt_SHOU GetAllCities() {
            object[] results = this.Invoke("GetAllCities", new object[0]);
            return ((ResponseBaseOfArrayOfCity63bt_SHOU)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCitiesAsync() {
            this.GetAllCitiesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCitiesAsync(object userState) {
            if ((this.GetAllCitiesOperationCompleted == null)) {
                this.GetAllCitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCitiesOperationCompleted);
            }
            this.InvokeAsync("GetAllCities", new object[0], this.GetAllCitiesOperationCompleted, userState);
        }
        
        private void OnGetAllCitiesOperationCompleted(object arg) {
            if ((this.GetAllCitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCitiesCompleted(this, new GetAllCitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILocationService/GetAllDistricts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfDistrict63bt_SHOU GetAllDistricts() {
            object[] results = this.Invoke("GetAllDistricts", new object[0]);
            return ((ResponseBaseOfArrayOfDistrict63bt_SHOU)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDistrictsAsync() {
            this.GetAllDistrictsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDistrictsAsync(object userState) {
            if ((this.GetAllDistrictsOperationCompleted == null)) {
                this.GetAllDistrictsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDistrictsOperationCompleted);
            }
            this.InvokeAsync("GetAllDistricts", new object[0], this.GetAllDistrictsOperationCompleted, userState);
        }
        
        private void OnGetAllDistrictsOperationCompleted(object arg) {
            if ((this.GetAllDistrictsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDistrictsCompleted(this, new GetAllDistrictsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfint {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private int responseDataField;
        
        private bool responseDataFieldSpecified;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseDataSpecified {
            get {
                return this.responseDataFieldSpecified;
            }
            set {
                this.responseDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Location")]
    public partial class District {
        
        private int cityIdField;
        
        private bool cityIdFieldSpecified;
        
        private int districtIdField;
        
        private bool districtIdFieldSpecified;
        
        private string districtNameField;
        
        private int municipalIdField;
        
        private bool municipalIdFieldSpecified;
        
        /// <remarks/>
        public int CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CityIdSpecified {
            get {
                return this.cityIdFieldSpecified;
            }
            set {
                this.cityIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int DistrictId {
            get {
                return this.districtIdField;
            }
            set {
                this.districtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistrictIdSpecified {
            get {
                return this.districtIdFieldSpecified;
            }
            set {
                this.districtIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        public int MunicipalId {
            get {
                return this.municipalIdField;
            }
            set {
                this.municipalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MunicipalIdSpecified {
            get {
                return this.municipalIdFieldSpecified;
            }
            set {
                this.municipalIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfArrayOfDistrict63bt_SHOU {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private District[] responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Location")]
        public District[] ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Location")]
    public partial class City {
        
        private int cityIdField;
        
        private bool cityIdFieldSpecified;
        
        private string cityNameField;
        
        private int provinceIdField;
        
        private bool provinceIdFieldSpecified;
        
        /// <remarks/>
        public int CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CityIdSpecified {
            get {
                return this.cityIdFieldSpecified;
            }
            set {
                this.cityIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public int ProvinceId {
            get {
                return this.provinceIdField;
            }
            set {
                this.provinceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProvinceIdSpecified {
            get {
                return this.provinceIdFieldSpecified;
            }
            set {
                this.provinceIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfArrayOfCity63bt_SHOU {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private City[] responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Location")]
        public City[] ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Location")]
    public partial class Province {
        
        private string provinceCenterField;
        
        private int provinceIdField;
        
        private bool provinceIdFieldSpecified;
        
        private string provinceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProvinceCenter {
            get {
                return this.provinceCenterField;
            }
            set {
                this.provinceCenterField = value;
            }
        }
        
        /// <remarks/>
        public int ProvinceId {
            get {
                return this.provinceIdField;
            }
            set {
                this.provinceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProvinceIdSpecified {
            get {
                return this.provinceIdFieldSpecified;
            }
            set {
                this.provinceIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProvinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfArrayOfProvince63bt_SHOU {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private Province[] responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Location")]
        public Province[] ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetLocationyVersionCompletedEventHandler(object sender, GetLocationyVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocationyVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocationyVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllProvincesCompletedEventHandler(object sender, GetAllProvincesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllProvincesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllProvincesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfProvince63bt_SHOU Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfProvince63bt_SHOU)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllCitiesCompletedEventHandler(object sender, GetAllCitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfCity63bt_SHOU Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfCity63bt_SHOU)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllDistrictsCompletedEventHandler(object sender, GetAllDistrictsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDistrictsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDistrictsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfDistrict63bt_SHOU Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfDistrict63bt_SHOU)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591