//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace ChiKoja.AdCommonService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IAdvertisementCommonService", Namespace="http://tempuri.org/")]
    public partial class AdvertisementCommonService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WhatTimeIsItOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestNameValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdvertisementCommonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerAdvertisementCommonOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveAdvertisementOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtendAdvertisementOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdvertisementCommonService() {
            this.Url = "http://192.168.42.16/Services/AdvertisementCommonService.svc/PublicService";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WhatTimeIsItCompletedEventHandler WhatTimeIsItCompleted;
        
        /// <remarks/>
        public event TestNameValueCompletedEventHandler TestNameValueCompleted;
        
        /// <remarks/>
        public event GetAdvertisementCommonCompletedEventHandler GetAdvertisementCommonCompleted;
        
        /// <remarks/>
        public event GetCustomerAdvertisementCommonCompletedEventHandler GetCustomerAdvertisementCommonCompleted;
        
        /// <remarks/>
        public event RemoveAdvertisementCompletedEventHandler RemoveAdvertisementCompleted;
        
        /// <remarks/>
        public event ExtendAdvertisementCompletedEventHandler ExtendAdvertisementCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementCommonService/WhatTimeIsIt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WhatTimeIsIt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            object[] results = this.Invoke("WhatTimeIsIt", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WhatTimeIsItAsync(string name) {
            this.WhatTimeIsItAsync(name, null);
        }
        
        /// <remarks/>
        public void WhatTimeIsItAsync(string name, object userState) {
            if ((this.WhatTimeIsItOperationCompleted == null)) {
                this.WhatTimeIsItOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhatTimeIsItOperationCompleted);
            }
            this.InvokeAsync("WhatTimeIsIt", new object[] {
                        name}, this.WhatTimeIsItOperationCompleted, userState);
        }
        
        private void OnWhatTimeIsItOperationCompleted(object arg) {
            if ((this.WhatTimeIsItCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WhatTimeIsItCompleted(this, new WhatTimeIsItCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementCommonService/TestNameValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TestNameValue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] userDictionary) {
            object[] results = this.Invoke("TestNameValue", new object[] {
                        name,
                        userDictionary});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestNameValueAsync(string name, ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] userDictionary) {
            this.TestNameValueAsync(name, userDictionary, null);
        }
        
        /// <remarks/>
        public void TestNameValueAsync(string name, ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] userDictionary, object userState) {
            if ((this.TestNameValueOperationCompleted == null)) {
                this.TestNameValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestNameValueOperationCompleted);
            }
            this.InvokeAsync("TestNameValue", new object[] {
                        name,
                        userDictionary}, this.TestNameValueOperationCompleted, userState);
        }
        
        private void OnTestNameValueOperationCompleted(object arg) {
            if ((this.TestNameValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestNameValueCompleted(this, new TestNameValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementCommonService/GetAdvertisementCommon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p GetAdvertisementCommon(int startIndex, [System.Xml.Serialization.XmlIgnoreAttribute()] bool startIndexSpecified, int count, [System.Xml.Serialization.XmlIgnoreAttribute()] bool countSpecified, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] userInput) {
            object[] results = this.Invoke("GetAdvertisementCommon", new object[] {
                        startIndex,
                        startIndexSpecified,
                        count,
                        countSpecified,
                        userInput});
            return ((ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdvertisementCommonAsync(int startIndex, bool startIndexSpecified, int count, bool countSpecified, ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] userInput) {
            this.GetAdvertisementCommonAsync(startIndex, startIndexSpecified, count, countSpecified, userInput, null);
        }
        
        /// <remarks/>
        public void GetAdvertisementCommonAsync(int startIndex, bool startIndexSpecified, int count, bool countSpecified, ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] userInput, object userState) {
            if ((this.GetAdvertisementCommonOperationCompleted == null)) {
                this.GetAdvertisementCommonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdvertisementCommonOperationCompleted);
            }
            this.InvokeAsync("GetAdvertisementCommon", new object[] {
                        startIndex,
                        startIndexSpecified,
                        count,
                        countSpecified,
                        userInput}, this.GetAdvertisementCommonOperationCompleted, userState);
        }
        
        private void OnGetAdvertisementCommonOperationCompleted(object arg) {
            if ((this.GetAdvertisementCommonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdvertisementCommonCompleted(this, new GetAdvertisementCommonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementCommonService/GetCustomerAdvertisementCommon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p GetCustomerAdvertisementCommon([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, bool userPassIsEncrypted, [System.Xml.Serialization.XmlIgnoreAttribute()] bool userPassIsEncryptedSpecified) {
            object[] results = this.Invoke("GetCustomerAdvertisementCommon", new object[] {
                        userName,
                        password,
                        userPassIsEncrypted,
                        userPassIsEncryptedSpecified});
            return ((ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerAdvertisementCommonAsync(string userName, string password, bool userPassIsEncrypted, bool userPassIsEncryptedSpecified) {
            this.GetCustomerAdvertisementCommonAsync(userName, password, userPassIsEncrypted, userPassIsEncryptedSpecified, null);
        }
        
        /// <remarks/>
        public void GetCustomerAdvertisementCommonAsync(string userName, string password, bool userPassIsEncrypted, bool userPassIsEncryptedSpecified, object userState) {
            if ((this.GetCustomerAdvertisementCommonOperationCompleted == null)) {
                this.GetCustomerAdvertisementCommonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerAdvertisementCommonOperationCompleted);
            }
            this.InvokeAsync("GetCustomerAdvertisementCommon", new object[] {
                        userName,
                        password,
                        userPassIsEncrypted,
                        userPassIsEncryptedSpecified}, this.GetCustomerAdvertisementCommonOperationCompleted, userState);
        }
        
        private void OnGetCustomerAdvertisementCommonOperationCompleted(object arg) {
            if ((this.GetCustomerAdvertisementCommonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerAdvertisementCommonCompleted(this, new GetCustomerAdvertisementCommonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementCommonService/RemoveAdvertisement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBase RemoveAdvertisement([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdvertisementCommon advertisementCommon) {
            object[] results = this.Invoke("RemoveAdvertisement", new object[] {
                        advertisementCommon});
            return ((ResponseBase)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveAdvertisementAsync(AdvertisementCommon advertisementCommon) {
            this.RemoveAdvertisementAsync(advertisementCommon, null);
        }
        
        /// <remarks/>
        public void RemoveAdvertisementAsync(AdvertisementCommon advertisementCommon, object userState) {
            if ((this.RemoveAdvertisementOperationCompleted == null)) {
                this.RemoveAdvertisementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveAdvertisementOperationCompleted);
            }
            this.InvokeAsync("RemoveAdvertisement", new object[] {
                        advertisementCommon}, this.RemoveAdvertisementOperationCompleted, userState);
        }
        
        private void OnRemoveAdvertisementOperationCompleted(object arg) {
            if ((this.RemoveAdvertisementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveAdvertisementCompleted(this, new RemoveAdvertisementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementCommonService/ExtendAdvertisement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBase ExtendAdvertisement([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdvertisementCommon advertisement) {
            object[] results = this.Invoke("ExtendAdvertisement", new object[] {
                        advertisement});
            return ((ResponseBase)(results[0]));
        }
        
        /// <remarks/>
        public void ExtendAdvertisementAsync(AdvertisementCommon advertisement) {
            this.ExtendAdvertisementAsync(advertisement, null);
        }
        
        /// <remarks/>
        public void ExtendAdvertisementAsync(AdvertisementCommon advertisement, object userState) {
            if ((this.ExtendAdvertisementOperationCompleted == null)) {
                this.ExtendAdvertisementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtendAdvertisementOperationCompleted);
            }
            this.InvokeAsync("ExtendAdvertisement", new object[] {
                        advertisement}, this.ExtendAdvertisementOperationCompleted, userState);
        }
        
        private void OnExtendAdvertisementOperationCompleted(object arg) {
            if ((this.ExtendAdvertisementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtendAdvertisementCompleted(this, new ExtendAdvertisementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBase {
        
        private string errorCodeField;
        
        private string messageField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public partial class Price {
        
        private PriceType priceTypeField;
        
        private bool priceTypeFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        /// <remarks/>
        public PriceType PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceTypeSpecified {
            get {
                return this.priceTypeFieldSpecified;
            }
            set {
                this.priceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public enum PriceType {
        
        /// <remarks/>
        ForSale,
        
        /// <remarks/>
        ForExchange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public partial class AdvertisementCommon {
        
        private int adPrivilageIdField;
        
        private bool adPrivilageIdFieldSpecified;
        
        private string advertisementCategoryField;
        
        private int advertisementCategoryIdField;
        
        private bool advertisementCategoryIdFieldSpecified;
        
        private string advertisementCommentsField;
        
        private string advertisementIdField;
        
        private string[] advertisementImagesField;
        
        private Price advertisementPriceField;
        
        private string advertisementStatusField;
        
        private int advertisementStatusIdField;
        
        private bool advertisementStatusIdFieldSpecified;
        
        private System.DateTime advertisementTimeField;
        
        private bool advertisementTimeFieldSpecified;
        
        private string advertisementTitleField;
        
        private string cityNameField;
        
        private int districtIdField;
        
        private bool districtIdFieldSpecified;
        
        private string districtNameField;
        
        private string emailField;
        
        private int numberOfVisitField;
        
        private bool numberOfVisitFieldSpecified;
        
        private string phoneNumberField;
        
        private string provinceNameField;
        
        private string userIdField;
        
        /// <remarks/>
        public int AdPrivilageId {
            get {
                return this.adPrivilageIdField;
            }
            set {
                this.adPrivilageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdPrivilageIdSpecified {
            get {
                return this.adPrivilageIdFieldSpecified;
            }
            set {
                this.adPrivilageIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementCategory {
            get {
                return this.advertisementCategoryField;
            }
            set {
                this.advertisementCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int AdvertisementCategoryId {
            get {
                return this.advertisementCategoryIdField;
            }
            set {
                this.advertisementCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvertisementCategoryIdSpecified {
            get {
                return this.advertisementCategoryIdFieldSpecified;
            }
            set {
                this.advertisementCategoryIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementComments {
            get {
                return this.advertisementCommentsField;
            }
            set {
                this.advertisementCommentsField = value;
            }
        }
        
        /// <remarks/>
        public string AdvertisementId {
            get {
                return this.advertisementIdField;
            }
            set {
                this.advertisementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] AdvertisementImages {
            get {
                return this.advertisementImagesField;
            }
            set {
                this.advertisementImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Price AdvertisementPrice {
            get {
                return this.advertisementPriceField;
            }
            set {
                this.advertisementPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementStatus {
            get {
                return this.advertisementStatusField;
            }
            set {
                this.advertisementStatusField = value;
            }
        }
        
        /// <remarks/>
        public int AdvertisementStatusId {
            get {
                return this.advertisementStatusIdField;
            }
            set {
                this.advertisementStatusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvertisementStatusIdSpecified {
            get {
                return this.advertisementStatusIdFieldSpecified;
            }
            set {
                this.advertisementStatusIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AdvertisementTime {
            get {
                return this.advertisementTimeField;
            }
            set {
                this.advertisementTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvertisementTimeSpecified {
            get {
                return this.advertisementTimeFieldSpecified;
            }
            set {
                this.advertisementTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementTitle {
            get {
                return this.advertisementTitleField;
            }
            set {
                this.advertisementTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public int DistrictId {
            get {
                return this.districtIdField;
            }
            set {
                this.districtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistrictIdSpecified {
            get {
                return this.districtIdFieldSpecified;
            }
            set {
                this.districtIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfVisit {
            get {
                return this.numberOfVisitField;
            }
            set {
                this.numberOfVisitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfVisitSpecified {
            get {
                return this.numberOfVisitFieldSpecified;
            }
            set {
                this.numberOfVisitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProvinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private AdvertisementCommon[] responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
        public AdvertisementCommon[] ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WhatTimeIsItCompletedEventHandler(object sender, WhatTimeIsItCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhatTimeIsItCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WhatTimeIsItCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TestNameValueCompletedEventHandler(object sender, TestNameValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestNameValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestNameValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAdvertisementCommonCompletedEventHandler(object sender, GetAdvertisementCommonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdvertisementCommonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdvertisementCommonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCustomerAdvertisementCommonCompletedEventHandler(object sender, GetCustomerAdvertisementCommonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerAdvertisementCommonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerAdvertisementCommonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfAdvertisementCommongJiz6K1p)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RemoveAdvertisementCompletedEventHandler(object sender, RemoveAdvertisementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveAdvertisementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveAdvertisementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ExtendAdvertisementCompletedEventHandler(object sender, ExtendAdvertisementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendAdvertisementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtendAdvertisementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBase)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591