//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace ChiKoja.AdTransportationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IAdvertisementTransportationService", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdvertisementBase))]
    public partial class AdvertisementTransportationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllVehiclesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdvertisementTransportationOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewAdvertisementTransportationOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditAdvertisementTransportationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTransportationBrandsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTransportationModelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServerDataVersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdvertisementTransportationService() {
            this.Url = "http://192.168.42.16/Services/AdvertisementTransportationService.svc/PublicServic" +
                "e";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllVehiclesCompletedEventHandler GetAllVehiclesCompleted;
        
        /// <remarks/>
        public event GetAdvertisementTransportationCompletedEventHandler GetAdvertisementTransportationCompleted;
        
        /// <remarks/>
        public event AddNewAdvertisementTransportationCompletedEventHandler AddNewAdvertisementTransportationCompleted;
        
        /// <remarks/>
        public event EditAdvertisementTransportationCompletedEventHandler EditAdvertisementTransportationCompleted;
        
        /// <remarks/>
        public event GetAllTransportationBrandsCompletedEventHandler GetAllTransportationBrandsCompleted;
        
        /// <remarks/>
        public event GetAllTransportationModelsCompletedEventHandler GetAllTransportationModelsCompleted;
        
        /// <remarks/>
        public event GetServerDataVersionCompletedEventHandler GetServerDataVersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementTransportationService/GetAllVehicles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfVehiclegJiz6K1p GetAllVehicles() {
            object[] results = this.Invoke("GetAllVehicles", new object[0]);
            return ((ResponseBaseOfArrayOfVehiclegJiz6K1p)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllVehiclesAsync() {
            this.GetAllVehiclesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllVehiclesAsync(object userState) {
            if ((this.GetAllVehiclesOperationCompleted == null)) {
                this.GetAllVehiclesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllVehiclesOperationCompleted);
            }
            this.InvokeAsync("GetAllVehicles", new object[0], this.GetAllVehiclesOperationCompleted, userState);
        }
        
        private void OnGetAllVehiclesOperationCompleted(object arg) {
            if ((this.GetAllVehiclesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllVehiclesCompleted(this, new GetAllVehiclesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementTransportationService/GetAdvertisementTransporta" +
            "tion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfAdvertisementTransportationgJiz6K1p GetAdvertisementTransportation(string AdvertisementGuid) {
            object[] results = this.Invoke("GetAdvertisementTransportation", new object[] {
                        AdvertisementGuid});
            return ((ResponseBaseOfAdvertisementTransportationgJiz6K1p)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdvertisementTransportationAsync(string AdvertisementGuid) {
            this.GetAdvertisementTransportationAsync(AdvertisementGuid, null);
        }
        
        /// <remarks/>
        public void GetAdvertisementTransportationAsync(string AdvertisementGuid, object userState) {
            if ((this.GetAdvertisementTransportationOperationCompleted == null)) {
                this.GetAdvertisementTransportationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdvertisementTransportationOperationCompleted);
            }
            this.InvokeAsync("GetAdvertisementTransportation", new object[] {
                        AdvertisementGuid}, this.GetAdvertisementTransportationOperationCompleted, userState);
        }
        
        private void OnGetAdvertisementTransportationOperationCompleted(object arg) {
            if ((this.GetAdvertisementTransportationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdvertisementTransportationCompleted(this, new GetAdvertisementTransportationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementTransportationService/AddNewAdvertisementTranspo" +
            "rtation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBase AddNewAdvertisementTransportation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdvertisementTransportation advertisementTransportation, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, bool userPassIsEncrypted, [System.Xml.Serialization.XmlIgnoreAttribute()] bool userPassIsEncryptedSpecified) {
            object[] results = this.Invoke("AddNewAdvertisementTransportation", new object[] {
                        advertisementTransportation,
                        userName,
                        password,
                        userPassIsEncrypted,
                        userPassIsEncryptedSpecified});
            return ((ResponseBase)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewAdvertisementTransportationAsync(AdvertisementTransportation advertisementTransportation, string userName, string password, bool userPassIsEncrypted, bool userPassIsEncryptedSpecified) {
            this.AddNewAdvertisementTransportationAsync(advertisementTransportation, userName, password, userPassIsEncrypted, userPassIsEncryptedSpecified, null);
        }
        
        /// <remarks/>
        public void AddNewAdvertisementTransportationAsync(AdvertisementTransportation advertisementTransportation, string userName, string password, bool userPassIsEncrypted, bool userPassIsEncryptedSpecified, object userState) {
            if ((this.AddNewAdvertisementTransportationOperationCompleted == null)) {
                this.AddNewAdvertisementTransportationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewAdvertisementTransportationOperationCompleted);
            }
            this.InvokeAsync("AddNewAdvertisementTransportation", new object[] {
                        advertisementTransportation,
                        userName,
                        password,
                        userPassIsEncrypted,
                        userPassIsEncryptedSpecified}, this.AddNewAdvertisementTransportationOperationCompleted, userState);
        }
        
        private void OnAddNewAdvertisementTransportationOperationCompleted(object arg) {
            if ((this.AddNewAdvertisementTransportationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewAdvertisementTransportationCompleted(this, new AddNewAdvertisementTransportationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementTransportationService/EditAdvertisementTransport" +
            "ation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBase EditAdvertisementTransportation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdvertisementTransportation advertisementTransportation) {
            object[] results = this.Invoke("EditAdvertisementTransportation", new object[] {
                        advertisementTransportation});
            return ((ResponseBase)(results[0]));
        }
        
        /// <remarks/>
        public void EditAdvertisementTransportationAsync(AdvertisementTransportation advertisementTransportation) {
            this.EditAdvertisementTransportationAsync(advertisementTransportation, null);
        }
        
        /// <remarks/>
        public void EditAdvertisementTransportationAsync(AdvertisementTransportation advertisementTransportation, object userState) {
            if ((this.EditAdvertisementTransportationOperationCompleted == null)) {
                this.EditAdvertisementTransportationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditAdvertisementTransportationOperationCompleted);
            }
            this.InvokeAsync("EditAdvertisementTransportation", new object[] {
                        advertisementTransportation}, this.EditAdvertisementTransportationOperationCompleted, userState);
        }
        
        private void OnEditAdvertisementTransportationOperationCompleted(object arg) {
            if ((this.EditAdvertisementTransportationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditAdvertisementTransportationCompleted(this, new EditAdvertisementTransportationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementTransportationService/GetAllTransportationBrands" +
            "", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfTransportationBrandoKnNwMS4 GetAllTransportationBrands() {
            object[] results = this.Invoke("GetAllTransportationBrands", new object[0]);
            return ((ResponseBaseOfArrayOfTransportationBrandoKnNwMS4)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTransportationBrandsAsync() {
            this.GetAllTransportationBrandsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTransportationBrandsAsync(object userState) {
            if ((this.GetAllTransportationBrandsOperationCompleted == null)) {
                this.GetAllTransportationBrandsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTransportationBrandsOperationCompleted);
            }
            this.InvokeAsync("GetAllTransportationBrands", new object[0], this.GetAllTransportationBrandsOperationCompleted, userState);
        }
        
        private void OnGetAllTransportationBrandsOperationCompleted(object arg) {
            if ((this.GetAllTransportationBrandsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTransportationBrandsCompleted(this, new GetAllTransportationBrandsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementTransportationService/GetAllTransportationModels" +
            "", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfArrayOfTransportationModeloKnNwMS4 GetAllTransportationModels() {
            object[] results = this.Invoke("GetAllTransportationModels", new object[0]);
            return ((ResponseBaseOfArrayOfTransportationModeloKnNwMS4)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTransportationModelsAsync() {
            this.GetAllTransportationModelsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTransportationModelsAsync(object userState) {
            if ((this.GetAllTransportationModelsOperationCompleted == null)) {
                this.GetAllTransportationModelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTransportationModelsOperationCompleted);
            }
            this.InvokeAsync("GetAllTransportationModels", new object[0], this.GetAllTransportationModelsOperationCompleted, userState);
        }
        
        private void OnGetAllTransportationModelsOperationCompleted(object arg) {
            if ((this.GetAllTransportationModelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTransportationModelsCompleted(this, new GetAllTransportationModelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAdvertisementTransportationService/GetServerDataVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseBaseOfint GetServerDataVersion() {
            object[] results = this.Invoke("GetServerDataVersion", new object[0]);
            return ((ResponseBaseOfint)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerDataVersionAsync() {
            this.GetServerDataVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetServerDataVersionAsync(object userState) {
            if ((this.GetServerDataVersionOperationCompleted == null)) {
                this.GetServerDataVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerDataVersionOperationCompleted);
            }
            this.InvokeAsync("GetServerDataVersion", new object[0], this.GetServerDataVersionOperationCompleted, userState);
        }
        
        private void OnGetServerDataVersionOperationCompleted(object arg) {
            if ((this.GetServerDataVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerDataVersionCompleted(this, new GetServerDataVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfArrayOfVehiclegJiz6K1p {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private Vehicle[] responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
        public Vehicle[] ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfint {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private int responseDataField;
        
        private bool responseDataFieldSpecified;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseDataSpecified {
            get {
                return this.responseDataFieldSpecified;
            }
            set {
                this.responseDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Transportation")]
    public partial class TransportationModel {
        
        private int brandIdField;
        
        private bool brandIdFieldSpecified;
        
        private int modelIdField;
        
        private bool modelIdFieldSpecified;
        
        private string modelNameField;
        
        /// <remarks/>
        public int BrandId {
            get {
                return this.brandIdField;
            }
            set {
                this.brandIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrandIdSpecified {
            get {
                return this.brandIdFieldSpecified;
            }
            set {
                this.brandIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ModelId {
            get {
                return this.modelIdField;
            }
            set {
                this.modelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelIdSpecified {
            get {
                return this.modelIdFieldSpecified;
            }
            set {
                this.modelIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfArrayOfTransportationModeloKnNwMS4 {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private TransportationModel[] responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Transportation")]
        public TransportationModel[] ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Transportation")]
    public partial class TransportationBrand {
        
        private int brandIdField;
        
        private bool brandIdFieldSpecified;
        
        private string brandNameField;
        
        /// <remarks/>
        public int BrandId {
            get {
                return this.brandIdField;
            }
            set {
                this.brandIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrandIdSpecified {
            get {
                return this.brandIdFieldSpecified;
            }
            set {
                this.brandIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfArrayOfTransportationBrandoKnNwMS4 {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private TransportationBrand[] responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements.Transportation")]
        public TransportationBrand[] ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBase {
        
        private string errorCodeField;
        
        private string messageField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public partial class Price {
        
        private PriceType priceTypeField;
        
        private bool priceTypeFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        /// <remarks/>
        public PriceType PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceTypeSpecified {
            get {
                return this.priceTypeFieldSpecified;
            }
            set {
                this.priceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public enum PriceType {
        
        /// <remarks/>
        ForSale,
        
        /// <remarks/>
        ForExchange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public partial class AdvertisementCommon {
        
        private int adPrivilageIdField;
        
        private bool adPrivilageIdFieldSpecified;
        
        private string advertisementCategoryField;
        
        private int advertisementCategoryIdField;
        
        private bool advertisementCategoryIdFieldSpecified;
        
        private string advertisementCommentsField;
        
        private string advertisementIdField;
        
        private string[] advertisementImagesField;
        
        private Price advertisementPriceField;
        
        private string advertisementStatusField;
        
        private int advertisementStatusIdField;
        
        private bool advertisementStatusIdFieldSpecified;
        
        private System.DateTime advertisementTimeField;
        
        private bool advertisementTimeFieldSpecified;
        
        private string advertisementTitleField;
        
        private string cityNameField;
        
        private int districtIdField;
        
        private bool districtIdFieldSpecified;
        
        private string districtNameField;
        
        private string emailField;
        
        private int numberOfVisitField;
        
        private bool numberOfVisitFieldSpecified;
        
        private string phoneNumberField;
        
        private string provinceNameField;
        
        private string userIdField;
        
        /// <remarks/>
        public int AdPrivilageId {
            get {
                return this.adPrivilageIdField;
            }
            set {
                this.adPrivilageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdPrivilageIdSpecified {
            get {
                return this.adPrivilageIdFieldSpecified;
            }
            set {
                this.adPrivilageIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementCategory {
            get {
                return this.advertisementCategoryField;
            }
            set {
                this.advertisementCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int AdvertisementCategoryId {
            get {
                return this.advertisementCategoryIdField;
            }
            set {
                this.advertisementCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvertisementCategoryIdSpecified {
            get {
                return this.advertisementCategoryIdFieldSpecified;
            }
            set {
                this.advertisementCategoryIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementComments {
            get {
                return this.advertisementCommentsField;
            }
            set {
                this.advertisementCommentsField = value;
            }
        }
        
        /// <remarks/>
        public string AdvertisementId {
            get {
                return this.advertisementIdField;
            }
            set {
                this.advertisementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] AdvertisementImages {
            get {
                return this.advertisementImagesField;
            }
            set {
                this.advertisementImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Price AdvertisementPrice {
            get {
                return this.advertisementPriceField;
            }
            set {
                this.advertisementPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementStatus {
            get {
                return this.advertisementStatusField;
            }
            set {
                this.advertisementStatusField = value;
            }
        }
        
        /// <remarks/>
        public int AdvertisementStatusId {
            get {
                return this.advertisementStatusIdField;
            }
            set {
                this.advertisementStatusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvertisementStatusIdSpecified {
            get {
                return this.advertisementStatusIdFieldSpecified;
            }
            set {
                this.advertisementStatusIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AdvertisementTime {
            get {
                return this.advertisementTimeField;
            }
            set {
                this.advertisementTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvertisementTimeSpecified {
            get {
                return this.advertisementTimeFieldSpecified;
            }
            set {
                this.advertisementTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdvertisementTitle {
            get {
                return this.advertisementTitleField;
            }
            set {
                this.advertisementTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public int DistrictId {
            get {
                return this.districtIdField;
            }
            set {
                this.districtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistrictIdSpecified {
            get {
                return this.districtIdFieldSpecified;
            }
            set {
                this.districtIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfVisit {
            get {
                return this.numberOfVisitField;
            }
            set {
                this.numberOfVisitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfVisitSpecified {
            get {
                return this.numberOfVisitFieldSpecified;
            }
            set {
                this.numberOfVisitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProvinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdvertisementTransportation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public partial class AdvertisementBase {
        
        private AdvertisementCommon advertisementCommonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AdvertisementCommon AdvertisementCommon {
            get {
                return this.advertisementCommonField;
            }
            set {
                this.advertisementCommonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public partial class AdvertisementTransportation : AdvertisementBase {
        
        private string bodyColorField;
        
        private BodyStatus bodyStatusField;
        
        private bool bodyStatusFieldSpecified;
        
        private string bodyStatusNameField;
        
        private int brandIdField;
        
        private bool brandIdFieldSpecified;
        
        private string brandNameField;
        
        private CarStatus carStatusField;
        
        private bool carStatusFieldSpecified;
        
        private string fuelNameField;
        
        private string gearboxField;
        
        private string internalColorField;
        
        private int makeYearField;
        
        private bool makeYearFieldSpecified;
        
        private int mileageField;
        
        private bool mileageFieldSpecified;
        
        private int modelIdField;
        
        private bool modelIdFieldSpecified;
        
        private string modelNameField;
        
        private PlateType plateTypeField;
        
        private bool plateTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BodyColor {
            get {
                return this.bodyColorField;
            }
            set {
                this.bodyColorField = value;
            }
        }
        
        /// <remarks/>
        public BodyStatus BodyStatus {
            get {
                return this.bodyStatusField;
            }
            set {
                this.bodyStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BodyStatusSpecified {
            get {
                return this.bodyStatusFieldSpecified;
            }
            set {
                this.bodyStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BodyStatusName {
            get {
                return this.bodyStatusNameField;
            }
            set {
                this.bodyStatusNameField = value;
            }
        }
        
        /// <remarks/>
        public int BrandId {
            get {
                return this.brandIdField;
            }
            set {
                this.brandIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrandIdSpecified {
            get {
                return this.brandIdFieldSpecified;
            }
            set {
                this.brandIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
        
        /// <remarks/>
        public CarStatus CarStatus {
            get {
                return this.carStatusField;
            }
            set {
                this.carStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarStatusSpecified {
            get {
                return this.carStatusFieldSpecified;
            }
            set {
                this.carStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FuelName {
            get {
                return this.fuelNameField;
            }
            set {
                this.fuelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gearbox {
            get {
                return this.gearboxField;
            }
            set {
                this.gearboxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InternalColor {
            get {
                return this.internalColorField;
            }
            set {
                this.internalColorField = value;
            }
        }
        
        /// <remarks/>
        public int MakeYear {
            get {
                return this.makeYearField;
            }
            set {
                this.makeYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MakeYearSpecified {
            get {
                return this.makeYearFieldSpecified;
            }
            set {
                this.makeYearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Mileage {
            get {
                return this.mileageField;
            }
            set {
                this.mileageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MileageSpecified {
            get {
                return this.mileageFieldSpecified;
            }
            set {
                this.mileageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ModelId {
            get {
                return this.modelIdField;
            }
            set {
                this.modelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelIdSpecified {
            get {
                return this.modelIdFieldSpecified;
            }
            set {
                this.modelIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
        
        /// <remarks/>
        public PlateType PlateType {
            get {
                return this.plateTypeField;
            }
            set {
                this.plateTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlateTypeSpecified {
            get {
                return this.plateTypeFieldSpecified;
            }
            set {
                this.plateTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public enum BodyStatus {
        
        /// <remarks/>
        NoAccident,
        
        /// <remarks/>
        OneAccident,
        
        /// <remarks/>
        TwoAccident,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public enum CarStatus {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Used,
        
        /// <remarks/>
        Draft,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public enum PlateType {
        
        /// <remarks/>
        National,
        
        /// <remarks/>
        FreeRegion,
        
        /// <remarks/>
        Temporary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService.Messages")]
    public partial class ResponseBaseOfAdvertisementTransportationgJiz6K1p {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] customDictionaryField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private AdvertisementTransportation responseDataField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] CustomDictionary {
            get {
                return this.customDictionaryField;
            }
            set {
                this.customDictionaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AdvertisementTransportation ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model.Advertisements")]
    public partial class Vehicle {
        
        private int brandIdField;
        
        private bool brandIdFieldSpecified;
        
        private string brandNameField;
        
        private int modelIdField;
        
        private bool modelIdFieldSpecified;
        
        private string modelNameField;
        
        /// <remarks/>
        public int BrandId {
            get {
                return this.brandIdField;
            }
            set {
                this.brandIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrandIdSpecified {
            get {
                return this.brandIdFieldSpecified;
            }
            set {
                this.brandIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
        
        /// <remarks/>
        public int ModelId {
            get {
                return this.modelIdField;
            }
            set {
                this.modelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModelIdSpecified {
            get {
                return this.modelIdFieldSpecified;
            }
            set {
                this.modelIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllVehiclesCompletedEventHandler(object sender, GetAllVehiclesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllVehiclesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllVehiclesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfVehiclegJiz6K1p Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfVehiclegJiz6K1p)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAdvertisementTransportationCompletedEventHandler(object sender, GetAdvertisementTransportationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdvertisementTransportationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdvertisementTransportationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfAdvertisementTransportationgJiz6K1p Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfAdvertisementTransportationgJiz6K1p)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddNewAdvertisementTransportationCompletedEventHandler(object sender, AddNewAdvertisementTransportationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewAdvertisementTransportationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewAdvertisementTransportationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EditAdvertisementTransportationCompletedEventHandler(object sender, EditAdvertisementTransportationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditAdvertisementTransportationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditAdvertisementTransportationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBase)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllTransportationBrandsCompletedEventHandler(object sender, GetAllTransportationBrandsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTransportationBrandsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTransportationBrandsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfTransportationBrandoKnNwMS4 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfTransportationBrandoKnNwMS4)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllTransportationModelsCompletedEventHandler(object sender, GetAllTransportationModelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTransportationModelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTransportationModelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfArrayOfTransportationModeloKnNwMS4 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfArrayOfTransportationModeloKnNwMS4)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetServerDataVersionCompletedEventHandler(object sender, GetServerDataVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerDataVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerDataVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseBaseOfint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseOfint)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591